### ISSUE TITLE
Use an SNS trigger instead of API Gateway?

### ISSUE THREAD

**Issue by sebastientromp** [awslabs/aws-serverless-java-container#145]
Hello,

This is a question, as I'm totally new to the SNS / SAM world. Is it possible to use an SNS topic as a trigger, instead of the API Gateway (ie the handler should be triggered when a message is broadcast to the SNS topic, instead of when a specific URL is called)?

Thanks for your help :)

Seb

**Comment by sebastientromp** [comment]
A few words on what I have done so far:

* The main handler implements now `RequestHandler<SNSEvent, Object>` 
* My sam.yaml is
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot API - com.zerotoheroes::populate-game-summary
Resources:
  PopulateGameSummaryFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.zerotoheroes.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/populate-game-summary-1.0-SNAPSHOT.jar
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        ReviewCreatedTopic:
          Type: SNS
          Properties:
            Topic: !Ref ReviewTopic
    ReviewTopic:
      Type: "AWS::SNS::Topic"
      Properties:
        DisplayName: "Test test"
```

At this stage I can't run sam local, because of the following error:

```
Ignoring PopulateGameSummaryFunction (com.zerotoheroes.StreamLambdaHandler::handleRequest) as no API event sources are defined
ERROR: None of the Serverless functions in your SAM template were able to be mounted. See above for errors.
```
I indeed don't want to expose an API endpoint - I'm only interested in triggering the function based on an SNS event.

I'll keep you updated if/when I make progress; in the meantime, any help is appreciated :)
