### ISSUE TITLE
Calling using SNS

### ISSUE THREAD

**Issue by KristofferSmedlund** [awslabs/aws-serverless-java-container#190]
* Framework version: 1.1.4
* Implementations: Spring Boot

## Scenario
Using SNS or simply the Invoke function to call the lambda function.

## Expected behavior
The call is mapped to a function in the controller in the Spring boot lambda function.

## Actual behavior
Nothing. Works well with the AWS API gateway though.

I'm assuming that the message sent is not formulated properly, so it's not mapped to the controller.
I can't really figure out how the mapping is done though. Since the input to Lambda is simply JSON, how should I formulate it so that the aws-serverless-java-container understands that it's a REST request and that it should be mapped to the controller?

**Comment by SAPessi** [comment]
Hey @KristofferSmedlund, apologies for the delay. The library is built to handle automatically the proxy events from API Gateway. You can make it handle custom events types by implementing your own [`RequestReader`](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/RequestReader.java) and [`ResponseWriter`](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/ResponseWriter.java) objects. Then, instead of using the static `getAwsProxyHandler()` method, you can use the [constructor of the `SpringLambdaContainerHandler` class](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-spring/src/main/java/com/amazonaws/serverless/proxy/spring/SpringLambdaContainerHandler.java#L113) passing your own implementations

**Comment by mattw-hestan** [comment]
I've found that the best way to handle different event types is to update the `template.yml` file to have multiple lambda functions with different handlers. So I leave the `StreamLambdaHandler` as it is, and I create a new `SnsEventLambdaHandler` class that implements `RequestHandler<SNSEvent, Response>` with a `Response handleRequest(final SNSEvent snsEvent, final Context context)` method. Update the template.yml to look like this:

```
  SpringBoot:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.example.StreamLambdaHandler::handleRequest
      Runtime: java8
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        PostApiExample:
          Type: Api
          Properties:
            Path: /example
            Method: POST
            RestApiId:
              Ref: MyApi

  SNS:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.example.SnsEventLambdaHandler::handleEvent
      Runtime: java8
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        SubtitleSnsEvent:
          Type: SNS
          Properties:
            Topic: arn:aws:sns:us-east-1:123456789101:exampleTopic
```

So any API Gateway request will get routed through the `StreamLambdaHandler` and any SNS event will get routed through the `SnsEventLambaHandler`. The down side to this is that you have two lambda functions.
